const $ = (id) => document.getElementById(id);
const storeKey = 'guardianSeniorAIConfigV4';
const logKey = 'guardianSeniorAILogV4';
const pinKey = 'guardianSeniorAIPinV4';
const modeKey = 'guardianSeniorAIModeV4';
const attemptKey = 'guardianSeniorAIPinAttemptsV4';
const emergencyWords = ['caido','caida','dolor pecho','pecho','mareo','no puedo','ayuda','socorro','me ahogo','respirar','sangre','inconsciente','ictus','infarto','mal','me he caido','no puedo levantarme'];
let lastEmergencyMessage = '';
let unlocked = false;

function normalizeText(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();}
function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function maskPhone(phone){const clean=String(phone||'').replace(/\s+/g,''); if(!clean)return 'No configurado'; return `••• ••• ${clean.slice(-3)}`;}
function sanitizePhone(phone){return String(phone||'').replace(/[^+0-9]/g,'').replace(/(?!^)\+/g,'');}
function getConfig(){try{return JSON.parse(localStorage.getItem(storeKey)||'{}');}catch{return {};}}
function saveConfig(){if(!unlocked)return alert('Desbloquea los ajustes con el PIN familiar.'); const config={elderName:$('elderName').value.trim().slice(0,60),phone1:sanitizePhone($('phone1').value),phone2:sanitizePhone($('phone2').value),medication:$('medication').value.trim().slice(0,700),emergencyText:$('emergencyText').value.trim().slice(0,240)}; localStorage.setItem(storeKey,JSON.stringify(config)); logEvent('Configuración actualizada','config'); updateShortcutUrl(); renderMaskedSummary(); speak('Configuración guardada.');}
function loadConfig(){const c=getConfig(); $('elderName').value=c.elderName||''; $('phone1').value=c.phone1||''; $('phone2').value=c.phone2||''; $('medication').value=c.medication||''; $('emergencyText').value=c.emergencyText||$('emergencyText').value; updateShortcutUrl(); renderMaskedSummary(); refreshLockUi(); applySavedModes();}
function renderMaskedSummary(){const c=getConfig(); const name=c.elderName?escapeHtml(c.elderName):'Persona no configurada'; const med=c.medication?'Notas médicas guardadas localmente':'Sin notas médicas'; $('maskedSummary').innerHTML=`<strong>${name}</strong><br>Familiar 1: ${maskPhone(c.phone1)}<br>Familiar 2: ${maskPhone(c.phone2)}<br>${med}`;}

function cryptoAvailable(){return window.crypto && crypto.subtle && window.TextEncoder;}
function randomSalt(){const a=new Uint8Array(16); crypto.getRandomValues(a); return btoa(String.fromCharCode(...a));}
function b64ToBytes(b64){return Uint8Array.from(atob(b64),c=>c.charCodeAt(0));}
function bytesToHex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function pbkdf2Hash(pin,saltB64){if(!cryptoAvailable())throw new Error('Crypto API no disponible'); const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']); const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:b64ToBytes(saltB64),iterations:150000,hash:'SHA-256'},key,256); return bytesToHex(bits);}
function getAttempts(){try{return JSON.parse(localStorage.getItem(attemptKey)||'{"count":0,"until":0}');}catch{return {count:0,until:0};}}
function setAttempts(v){localStorage.setItem(attemptKey,JSON.stringify(v));}
function isLockedOut(){const a=getAttempts(); return Date.now()<Number(a.until||0);}
function lockoutText(){const a=getAttempts(); const sec=Math.ceil((Number(a.until||0)-Date.now())/1000); return sec>0?`Demasiados intentos. Espera ${sec} segundos.`:'';}
function noteFailedAttempt(){const a=getAttempts(); a.count=(a.count||0)+1; if(a.count>=5){a.until=Date.now()+60000; a.count=0;} setAttempts(a);}
function clearAttempts(){localStorage.removeItem(attemptKey);}

async function createPin(){const pin=$('newPin').value.trim(); if(!/^\d{4,8}$/.test(pin))return alert('El PIN debe tener entre 4 y 8 números.'); if(!cryptoAvailable())return alert('Este navegador no permite crear un PIN seguro. Usa Safari/Chrome actualizado y, preferiblemente, GitHub Pages con HTTPS.'); const salt=randomSalt(); const hash=await pbkdf2Hash(pin,salt); localStorage.setItem(pinKey,JSON.stringify({salt,hash,iterations:150000,algo:'PBKDF2-SHA256'})); $('newPin').value=''; unlocked=true; clearAttempts(); refreshLockUi(); logEvent('PIN familiar creado','security'); speak('PIN creado. Ajustes desbloqueados.');}
async function unlockSettings(){if(isLockedOut()){ $('pinHelp').textContent=lockoutText(); return; } const stored=localStorage.getItem(pinKey); if(!stored)return refreshLockUi(); const data=JSON.parse(stored); const pin=$('pinInput').value.trim(); const hash=await pbkdf2Hash(pin,data.salt); if(hash!==data.hash){noteFailedAttempt(); $('pinInput').value=''; $('pinHelp').textContent=lockoutText()||'PIN incorrecto.'; logEvent('Intento de desbloqueo fallido','security'); return;} $('pinInput').value=''; unlocked=true; clearAttempts(); refreshLockUi(); logEvent('Ajustes desbloqueados','security');}
function lockSettings(){unlocked=false; refreshLockUi();}
function refreshLockUi(){const hasPin=Boolean(localStorage.getItem(pinKey)); $('pinSetup').classList.toggle('hidden',hasPin); $('pinGate').classList.toggle('hidden',!hasPin||unlocked); $('settingsPanel').classList.toggle('hidden',!unlocked); $('lockState').textContent=unlocked?'Desbloqueada':'Bloqueada'; $('lockState').className=unlocked?'pill unlocked':'pill locked'; $('pinHelp').textContent=isLockedOut()?lockoutText():'';}

function logEvent(text,type='event'){let logs=[]; try{logs=JSON.parse(localStorage.getItem(logKey)||'[]');}catch{} logs.unshift({text:String(text).slice(0,130),type,date:new Date().toLocaleString('es-ES')}); localStorage.setItem(logKey,JSON.stringify(logs.slice(0,80))); renderLog();}
function renderLog(){let logs=[]; try{logs=JSON.parse(localStorage.getItem(logKey)||'[]');}catch{} $('eventLog').innerHTML=logs.map(i=>`<li><strong>${escapeHtml(i.date)}</strong> — ${escapeHtml(i.text)}</li>`).join('')||'<li>Sin eventos.</li>';}
function setStatus(text){$('systemStatus').textContent=text;}
function speak(text){if(!('speechSynthesis'in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='es-ES'; u.rate=.9; speechSynthesis.speak(u);}
function getLocation(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null); navigator.geolocation.getCurrentPosition(pos=>resolve(pos.coords),()=>resolve(null),{enableHighAccuracy:true,timeout:9000,maximumAge:60000});});}
function locationText(coords){if(!coords)return 'Ubicación no disponible'; return `Ubicación: https://maps.google.com/?q=${coords.latitude},${coords.longitude}`;}
async function buildEmergencyMessage(reason=''){const c=getConfig(); const coords=await getLocation(); const name=c.elderName||'La persona'; const base=c.emergencyText||'Necesito ayuda. Puede que me haya caído o me encuentre mal.'; return `${name}: ${base}${reason?' Motivo: '+String(reason).slice(0,90):''}. ${locationText(coords)}`;}
async function activateEmergency(reason='Emergencia manual'){setStatus('Emergencia'); lastEmergencyMessage=await buildEmergencyMessage(reason); $('emergencySummary').textContent=lastEmergencyMessage; logEvent(`Emergencia activada: ${String(reason).slice(0,60)}`,'emergency'); speak('Emergencia activada. Puedes llamar al 112, llamar a la familia o enviar un mensaje.'); const c=getConfig(); $('callPrimaryBtn').disabled=!c.phone1; $('callSecondaryBtn').disabled=!c.phone2; $('sendSmsBtn').disabled=!c.phone1; if(!$('emergencyDialog').open)$('emergencyDialog').showModal();}
function callNumber(phone){const clean=sanitizePhone(phone); if(!clean)return alert('Teléfono no configurado.'); location.href=`tel:${clean}`;}
function callPrimary(){callNumber(getConfig().phone1);}
function callSecondary(){callNumber(getConfig().phone2);}
function call112(){location.href='tel:112';}
function sendSms(){const phone=sanitizePhone(getConfig().phone1); if(!phone)return alert('Configura primero un teléfono familiar.'); const body=encodeURIComponent(lastEmergencyMessage||$('emergencyText').value); location.href=`sms:${phone}&body=${body}`;}
function copyEmergencyMessage(){navigator.clipboard?.writeText(lastEmergencyMessage||'').then(()=>speak('Mensaje copiado.')).catch(()=>alert('No se pudo copiar automáticamente.'));}
function prepareSmsTest(){if(!unlocked)return alert('Desbloquea los ajustes para hacer pruebas.'); buildEmergencyMessage('Prueba de funcionamiento').then(msg=>{lastEmergencyMessage=msg; $('emergencySummary').textContent=msg; sendSms();});}
function analyzeText(text){text=String(text||'').trim(); if(!text){$('analysisBox').innerHTML='<strong>Mensaje vacío.</strong> Escribe o dicta qué ocurre antes de analizar.'; speak('No hay ningún mensaje para analizar.'); return;} const normalized=normalizeText(text); const risk=emergencyWords.some(w=>normalized.includes(normalizeText(w))); if(risk){$('analysisBox').innerHTML='<strong>Riesgo detectado.</strong> Si hay peligro inmediato, llama al 112. También puedes avisar a un familiar.'; activateEmergency(text);}else{$('analysisBox').innerHTML='<strong>No parece emergencia.</strong> Se registra como comprobación normal.'; logEvent('Mensaje analizado sin emergencia','check'); speak('No parece una emergencia. Queda registrado.');}}
function startListening(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SpeechRecognition)return alert('Este navegador no soporta reconocimiento de voz. En iPhone usa Siri con Atajos o escribe el mensaje.'); const r=new SpeechRecognition(); r.lang='es-ES'; r.interimResults=false; r.maxAlternatives=1; setStatus('Escuchando'); speak('Te escucho. Dime qué ocurre.'); r.onresult=e=>{const text=e.results[0][0].transcript; $('messageInput').value=text; setStatus('Analizando'); analyzeText(text);}; r.onerror=()=>setStatus('Lista'); r.onend=()=>setStatus('Lista'); r.start();}
function updateShortcutUrl(){const url=new URL(location.href); url.searchParams.set('sos','1'); $('shortcutUrl').textContent=url.href;}
function exportLog(){if(!unlocked)return alert('Desbloquea los ajustes para exportar el registro.'); const blob=new Blob([localStorage.getItem(logKey)||'[]'],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='guardian-senior-ai-registro.json'; a.click(); URL.revokeObjectURL(a.href);}
function clearLog(){if(!unlocked)return alert('Desbloquea los ajustes para borrar el registro.'); if(!confirm('¿Borrar el registro local?'))return; localStorage.removeItem(logKey); renderLog();}
async function wipeAllData(){const stored=localStorage.getItem(pinKey); if(stored){const pin=prompt('Introduce el PIN familiar para borrar todos los datos:'); if(!pin)return; const data=JSON.parse(stored); if(await pbkdf2Hash(pin,data.salt)!==data.hash)return alert('PIN incorrecto. No se ha borrado nada.');} if(!confirm('Esto eliminará contactos, medicación, PIN e historial de este dispositivo. ¿Continuar?'))return; [storeKey,logKey,pinKey,modeKey,attemptKey].forEach(k=>localStorage.removeItem(k)); unlocked=false; loadConfig(); renderLog(); speak('Datos borrados.');}
function applySavedModes(){let modes={}; try{modes=JSON.parse(localStorage.getItem(modeKey)||'{}');}catch{} document.body.classList.toggle('high-contrast',Boolean(modes.highContrast)); document.body.classList.toggle('simple-mode',Boolean(modes.simpleMode));}
function saveModes(){localStorage.setItem(modeKey,JSON.stringify({highContrast:document.body.classList.contains('high-contrast'),simpleMode:document.body.classList.contains('simple-mode')}));}

$('createPinBtn').addEventListener('click',createPin); $('unlockBtn').addEventListener('click',unlockSettings); $('lockBtn').addEventListener('click',lockSettings); $('saveConfigBtn').addEventListener('click',saveConfig); $('sosBtn').addEventListener('click',()=>activateEmergency('Botón SOS')); $('call112Btn').addEventListener('click',call112); $('safeBtn').addEventListener('click',()=>{logEvent('La persona indicó que está bien','safe'); speak('Me alegro. Queda registrado que estás bien.'); setStatus('Bien');}); $('listenBtn').addEventListener('click',startListening); $('analyzeBtn').addEventListener('click',()=>analyzeText($('messageInput').value||'')); $('readLastBtn').addEventListener('click',()=>speak($('analysisBox').textContent)); $('testSmsBtn').addEventListener('click',prepareSmsTest); $('callPrimaryBtn').addEventListener('click',callPrimary); $('callSecondaryBtn').addEventListener('click',callSecondary); $('sendSmsBtn').addEventListener('click',sendSms); $('copyMsgBtn').addEventListener('click',copyEmergencyMessage); $('closeDialogBtn').addEventListener('click',()=>$('emergencyDialog').close()); $('clearLogBtn').addEventListener('click',clearLog); $('exportLogBtn').addEventListener('click',exportLog); $('wipeDataBtn').addEventListener('click',wipeAllData); $('toggleMode').addEventListener('click',()=>{document.body.classList.toggle('high-contrast'); saveModes();}); $('toggleSimpleMode').addEventListener('click',()=>{document.body.classList.toggle('simple-mode'); saveModes();}); $('copyShortcutBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('shortcutUrl').textContent); speak('Enlace copiado.');}catch{alert('No se pudo copiar automáticamente. Mantén pulsado el enlace y cópialo manualmente.');}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
loadConfig(); renderLog(); if(new URLSearchParams(location.search).get('sos')==='1')setTimeout(()=>activateEmergency('Atajo de iPhone o enlace SOS'),600);
